[build]
  command = "npm run build"
  publish = "dist"
  edge_functions = "netlify/edge-functions"

[dev]
  command = "npm run dev:ui"
  targetPort = 5173
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
